import type { CoreBehaviorResult, CoreErrorCode } from '../../behaviors/core-safe-error.ts';
import { createCoreSafeError } from '../../behaviors/core-safe-error.ts';
import { enforceCoreGovernedAction, type CoreAuditContext, type CoreHumanReviewContext, type CorePermissionContext, type CorePolicyContext } from '../../behaviors/core-governance-behavior.ts';
import { CoreIdempotencyRegistry } from '../../behaviors/core-idempotency-behavior.ts';
import { paginateCoreItems, type CoreEventTraceRecord } from '../../behaviors/core-event-pagination-behavior.ts';
import { type CoreReferenceRecord, CoreReferenceRegistry } from '../../behaviors/core-reference-behavior.ts';
import { validateCoreMvpObjectBaseRecord } from '../../objects/core-mvp-object-validation.ts';
import type { CoreMvpObjectBaseRecord } from '../../objects/core-mvp-object-base-record.ts';
import type { CoreObjectStatus } from '../../objects/core-object-status.ts';
import { createCoreObjectId, createCoreObjectType } from '../../objects/index.ts';
import { CORE_EVENT_ACTIONS, createCoreEventType, type CoreEventId } from '../../events/index.ts';

export const CORE_CUSTOMER_TYPES = ['Individual', 'Company', 'AgencyClient', 'InternalClient', 'Unknown'] as const;
export type CoreCustomerType = (typeof CORE_CUSTOMER_TYPES)[number];
export const CORE_CUSTOMER_STATUSES = ['Draft', 'Active', 'ReviewRequired', 'Suspended', 'Inactive', 'Archived', 'DeletedReferenceOnly'] as const;
export type CoreCustomerStatus = (typeof CORE_CUSTOMER_STATUSES)[number];
export const CORE_CUSTOMER_STATUS_TO_OBJECT_STATUS: Record<CoreCustomerStatus, CoreObjectStatus> = {
  Draft: 'draft', ReviewRequired: 'draft', Active: 'active', Suspended: 'inactive', Inactive: 'inactive', Archived: 'archived', DeletedReferenceOnly: 'deleted'
};
export const CORE_CUSTOMER_IMPLEMENTED_OPERATIONS = ['createCustomer', 'getCustomer', 'listCustomers', 'validateCustomerReference', 'changeCustomerStatus'] as const;
export const CORE_CUSTOMER_MINIMUM_CAPABILITIES = ['create where required', 'read where required', 'search/list where required', 'validate_reference', 'basic status transition where required', 'permission check hook', 'policy check hook', 'safe error return', 'event trace handoff where applicable', 'idempotency handling where duplicate-sensitive'] as const;
const CONTRACT_ID = 'core-service-customer-service-contract';
const opaque = /^[A-Za-z0-9][A-Za-z0-9:_./-]{2,127}$/;
const transitions = new Set(['Draft->Active','Draft->ReviewRequired','ReviewRequired->Active','Active->Suspended','Suspended->Active','Active->Inactive','Inactive->Active','Inactive->Archived','Active->Archived','Archived->DeletedReferenceOnly']);

export interface CoreCustomerServiceRecord { readonly objectRecord: CoreMvpObjectBaseRecord; readonly customerType: CoreCustomerType; readonly customerStatus: CoreCustomerStatus; readonly nameReference: string; readonly sourceReference: string; }
export interface CoreCustomerGovernanceContext { readonly permission: CorePermissionContext; readonly policy: CorePolicyContext; readonly review: CoreHumanReviewContext; readonly audit: CoreAuditContext; readonly auditContextReferenceId: string; readonly correlationId: string; }
export interface CoreCustomerServiceStore { get(customerReferenceId: string): CoreCustomerServiceRecord | undefined; list(): readonly CoreCustomerServiceRecord[]; insert(record: CoreCustomerServiceRecord): CoreBehaviorResult<CoreCustomerServiceRecord>; replace(record: CoreCustomerServiceRecord): CoreBehaviorResult<CoreCustomerServiceRecord>; }
export interface CoreCustomerEventTracePort { append(record: CoreEventTraceRecord): CoreBehaviorResult<CoreEventTraceRecord>; }
export interface CoreCustomerServiceDependencies { readonly store: CoreCustomerServiceStore; readonly idempotencyRegistry: CoreIdempotencyRegistry; readonly eventTracePort: CoreCustomerEventTracePort; readonly relatedReferenceRegistry: CoreReferenceRegistry; readonly now: () => string; readonly eventIdFactory: (operation: 'createCustomer' | 'changeCustomerStatus', customerReferenceId: string, idempotencyKey: string) => CoreEventId; readonly cursorSecret: string; }
export interface CoreCustomerListSummary { readonly publicReferenceId: string; readonly customerType: CoreCustomerType; readonly customerStatus: CoreCustomerStatus; readonly genericObjectStatus: CoreObjectStatus | undefined; readonly createdAt: string; readonly updatedAt?: string; }
export interface CoreCustomerReferenceValidationResult { readonly isValid: boolean; readonly customerReferenceId: string; readonly customerType: CoreCustomerType | null; readonly customerStatus: CoreCustomerStatus | null; readonly reasonCode: 'Valid'|'NotFound'|'Draft'|'ReviewRequired'|'Suspended'|'Inactive'|'Archived'|'DeletedReferenceOnly'|'InvalidReference'; }

function safe<T>(code: CoreErrorCode, message: string, correlationId?: string | null): CoreBehaviorResult<T> { return { ok: false, error: createCoreSafeError({ code, category: 'Validation', message, correlationId }) }; }
function freeze<T>(v: T): T { if (typeof v === 'object' && v) { for (const item of Object.values(v)) freeze(item); return Object.freeze(v); } return v; }
function clone<T>(v: T): T { return structuredClone(v); }
function isType(v: string): v is CoreCustomerType { return (CORE_CUSTOMER_TYPES as readonly string[]).includes(v); }
function isStatus(v: string): v is CoreCustomerStatus { return (CORE_CUSTOMER_STATUSES as readonly string[]).includes(v); }
function ensureGov(ctx: CoreCustomerGovernanceContext, op: string, perm: string, scope: string, target: string): CoreBehaviorResult<unknown> {
  if (ctx.correlationId !== ctx.permission.correlationId || ctx.correlationId !== ctx.policy.correlationId || ctx.correlationId !== ctx.audit.correlationId) return safe('ValidationFailed','Correlation IDs must match.',ctx.correlationId);
  if (ctx.permission.intendedOperation !== op || !ctx.permission.requiredPermissionKeys.includes(perm)) return safe('PermissionDenied','Required permission is missing.',ctx.correlationId);
  if (ctx.policy.intendedOperation !== op || !ctx.policy.requiredPolicyScopes.includes(scope)) return safe('PolicyRestricted','Required policy scope is missing.',ctx.correlationId);
  if (ctx.audit.operationName !== op || ctx.audit.targetObjectType !== 'customer-record' || ctx.audit.targetObjectReferenceId !== target || !opaque.test(ctx.auditContextReferenceId)) return safe('AuditContextMissing','Audit context is missing.',ctx.correlationId);
  return enforceCoreGovernedAction({ permission: ctx.permission, policy: ctx.policy, review: ctx.review, audit: ctx.audit });
}
function validateRecord(r: CoreCustomerServiceRecord, ref: CoreReferenceRecord, reg: CoreReferenceRegistry): CoreBehaviorResult<CoreCustomerServiceRecord> {
  if (!isType(r.customerType)) return safe('InvalidCustomerType','Customer type is invalid.', r.objectRecord.auditMetadata.correlationId);
  if (!isStatus(r.customerStatus)) return safe('InvalidCustomerStatus','Customer status is invalid.', r.objectRecord.auditMetadata.correlationId);
  if (r.objectRecord.domainId !== 'customer' || r.objectRecord.objectType !== 'customer-record' || r.objectRecord.objectContractId !== 'core-object-customer-record-contract' || r.objectRecord.publicReferenceId !== ref.referenceId) return safe('CustomerObjectMismatch','Customer Object foundation does not match.', r.objectRecord.auditMetadata.correlationId);
  if (r.objectRecord.status !== CORE_CUSTOMER_STATUS_TO_OBJECT_STATUS[r.customerStatus]) return safe('CustomerObjectMismatch','Customer and Object statuses are inconsistent.', r.objectRecord.auditMetadata.correlationId);
  if (!r.nameReference.trim() || r.nameReference.length > 128) return safe('CustomerNameRequired','Customer name reference is required.', r.objectRecord.auditMetadata.correlationId);
  if (!opaque.test(r.sourceReference)) return safe('CustomerSourceReferenceRequired','Customer source reference is required.', r.objectRecord.auditMetadata.correlationId);
  const validation = validateCoreMvpObjectBaseRecord(r.objectRecord, { publicReferenceRecord: ref, relatedReferenceRegistry: reg });
  if (!validation.ok) return safe('ValidationFailed','Customer Object base record is invalid.', r.objectRecord.auditMetadata.correlationId);
  return { ok: true, value: freeze(clone(r)) };
}
export class CoreInMemoryCustomerServiceStore implements CoreCustomerServiceStore { #records = new Map<string, CoreCustomerServiceRecord>(); get(id: string) { const r = this.#records.get(id); return r ? freeze(clone(r)) : undefined; } list() { return [...this.#records.values()].map((r) => freeze(clone(r))); } insert(r: CoreCustomerServiceRecord): CoreBehaviorResult<CoreCustomerServiceRecord> { if (this.#records.has(r.objectRecord.publicReferenceId)) return safe('CustomerAlreadyExists','Customer already exists.', r.objectRecord.auditMetadata.correlationId); const s = freeze(clone(r)); this.#records.set(r.objectRecord.publicReferenceId, s); return { ok: true, value: freeze(clone(s)) }; } replace(r: CoreCustomerServiceRecord): CoreBehaviorResult<CoreCustomerServiceRecord> { if (!this.#records.has(r.objectRecord.publicReferenceId)) return safe('CustomerNotFound','Customer was not found.', r.objectRecord.auditMetadata.correlationId); const s = freeze(clone(r)); this.#records.set(r.objectRecord.publicReferenceId, s); return { ok: true, value: freeze(clone(s)) }; } }
export class CoreCustomerService { constructor(readonly deps: CoreCustomerServiceDependencies) {}
 createCustomer(input: { readonly objectRecord: CoreMvpObjectBaseRecord; readonly publicReferenceRecord: CoreReferenceRecord; readonly customerType: string; readonly customerStatus: string; readonly nameReference: string; readonly sourceReference: string; readonly idempotencyKey?: string | null; readonly governance: CoreCustomerGovernanceContext; }): CoreBehaviorResult<CoreCustomerServiceRecord> {
  const target = input.objectRecord.publicReferenceId;
  const gov = ensureGov(input.governance, 'customer.create', 'customer:create', 'customer.write', target);
  if (!gov.ok) return gov;
  if (!['Draft', 'ReviewRequired', 'Active'].includes(input.customerStatus)) return safe('InvalidCustomerStatus', 'Initial Customer status is invalid.', input.governance.correlationId);
  const idem = this.deps.idempotencyRegistry.execute({ idempotencyKey: input.idempotencyKey, idempotencyScope: 'customer-service', operationName: 'createCustomer', request: { objectRecord: input.objectRecord, customerType: input.customerType, customerStatus: input.customerStatus, nameReference: input.nameReference, sourceReference: input.sourceReference }, permissionAllowed: true, policyAllowed: true, correlationId: input.governance.correlationId }, () => {
    if (this.deps.store.get(target)) return safe<CoreCustomerServiceRecord>('CustomerAlreadyExists', 'Customer already exists.', input.governance.correlationId);
    const rec = { objectRecord: input.objectRecord, customerType: input.customerType as CoreCustomerType, customerStatus: input.customerStatus as CoreCustomerStatus, nameReference: input.nameReference, sourceReference: input.sourceReference };
    const valid = validateRecord(rec, input.publicReferenceRecord, this.deps.relatedReferenceRegistry);
    if (!valid.ok) return valid;
    const event = this.deps.eventTracePort.append({ auditContextReferenceId: input.governance.auditContextReferenceId, visibility: 'Internal', event: { id: this.deps.eventIdFactory('createCustomer', target, input.idempotencyKey ?? ''), type: createCoreEventType('core-object-created'), action: CORE_EVENT_ACTIONS.created, domainId: 'customer', object: { id: createCoreObjectId(target), type: createCoreObjectType('customer-record'), domainId: 'customer' }, source: { actorType: 'service', actorId: CONTRACT_ID }, occurredAt: this.deps.now(), correlationId: input.governance.correlationId, payload: { customerReferenceId: target, customerType: input.customerType, customerStatus: input.customerStatus } } });
    if (!event.ok) return safe<CoreCustomerServiceRecord>('EventTraceFailed', 'Event trace failed.', input.governance.correlationId);
    return this.deps.store.insert(valid.value);
  });
  return idem.ok ? idem.value.result : idem;
}
 getCustomer(input:{readonly customerReferenceId:string; readonly governance:CoreCustomerGovernanceContext}):CoreBehaviorResult<CoreCustomerServiceRecord>{ const gov=ensureGov(input.governance,'customer.read','customer:read','customer.read',input.customerReferenceId); if(!gov.ok) return gov; const ref=this.deps.relatedReferenceRegistry.resolve({referenceId:input.customerReferenceId,expectedObjectType:'customer-record',expectedDomain:'customer'}); if(!ref.ok) return safe('InvalidCustomerReference','Customer reference is invalid.',input.governance.correlationId); const r=this.deps.store.get(input.customerReferenceId); if(!r||r.customerStatus==='DeletedReferenceOnly') return safe('CustomerNotFound','Customer was not found.',input.governance.correlationId); return {ok:true,value:r};}
 listCustomers(input:{readonly filters?:{readonly customerType?:CoreCustomerType;readonly customerStatus?:CoreCustomerStatus;readonly publicReferenceId?:string};readonly pagination?:{readonly cursor?:string|null;readonly limit?:number|null;readonly sortField?:string|null;readonly sortDirection?:'Asc'|'Desc'|null;readonly includeTotalCount?:boolean|null};readonly governance:CoreCustomerGovernanceContext}) { const gov=ensureGov(input.governance,'customer.list','customer:list','customer.list',input.governance.audit.targetObjectReferenceId); if(!gov.ok) return gov; const items=this.deps.store.list().filter(r=>(!input.filters?.customerType||r.customerType===input.filters.customerType)&&(!input.filters?.customerStatus||r.customerStatus===input.filters.customerStatus)&&(!input.filters?.publicReferenceId||r.objectRecord.publicReferenceId===input.filters.publicReferenceId)).map(r=>({publicReferenceId:r.objectRecord.publicReferenceId,customerType:r.customerType,customerStatus:r.customerStatus,genericObjectStatus:r.objectRecord.status,createdAt:r.objectRecord.auditMetadata.createdAt,updatedAt:r.objectRecord.auditMetadata.updatedAt})); return paginateCoreItems(items,input.pagination??{}, {permissionAllowed:true,policyAllowed:true,actorReferenceId:input.governance.permission.actorReferenceId,allowedSortFields:['publicReferenceId','customerType','customerStatus'],totalCountAllowed:true,correlationId:input.governance.correlationId}, {queryKey:JSON.stringify(input.filters??{}),cursorSecret:this.deps.cursorSecret,visible:()=>true});}
 validateCustomerReference(input:{readonly customerReferenceId:string;readonly requestingDomain:string;readonly requestingService:string;readonly governance:CoreCustomerGovernanceContext}):CoreBehaviorResult<CoreCustomerReferenceValidationResult>{ const gov=ensureGov(input.governance,'customer.validate_reference','customer:validate_reference','customer.reference',input.customerReferenceId); if(!gov.ok) return gov; if(!opaque.test(input.customerReferenceId)) return {ok:true,value:{isValid:false,customerReferenceId:input.customerReferenceId,customerType:null,customerStatus:null,reasonCode:'InvalidReference'}}; const r=this.deps.store.get(input.customerReferenceId); if(!r) return {ok:true,value:{isValid:false,customerReferenceId:input.customerReferenceId,customerType:null,customerStatus:null,reasonCode:'NotFound'}}; return {ok:true,value:{isValid:r.customerStatus==='Active',customerReferenceId:input.customerReferenceId,customerType:r.customerType,customerStatus:r.customerStatus,reasonCode:r.customerStatus==='Active'?'Valid':r.customerStatus}};}
 changeCustomerStatus(input:{readonly customerReferenceId:string;readonly targetStatus:CoreCustomerStatus;readonly reasonReference?:string|null;readonly idempotencyKey?:string|null;readonly governance:CoreCustomerGovernanceContext}):CoreBehaviorResult<CoreCustomerServiceRecord>{ const gov=ensureGov(input.governance,'customer.change_status','customer:change_status','customer.lifecycle',input.customerReferenceId); if(!gov.ok) return gov; const existing=this.deps.store.get(input.customerReferenceId); if(!existing) return safe('CustomerNotFound','Customer was not found.',input.governance.correlationId); const pair=`${existing.customerStatus}->${input.targetStatus}`; if(!transitions.has(pair)) return safe('InvalidCustomerTransition','Customer status transition is invalid.',input.governance.correlationId); if(['Suspended','Inactive','Archived','DeletedReferenceOnly'].includes(input.targetStatus)&&(!input.reasonReference||!opaque.test(input.reasonReference))) return safe('CustomerReasonReferenceRequired','Customer reason reference is required.',input.governance.correlationId); const idem=this.deps.idempotencyRegistry.execute({idempotencyKey:input.idempotencyKey,idempotencyScope:'customer-service',operationName:'changeCustomerStatus',request:{customerReferenceId:input.customerReferenceId,targetStatus:input.targetStatus,reasonReference:input.reasonReference},permissionAllowed:true,policyAllowed:true,correlationId:input.governance.correlationId},()=>{ const now=this.deps.now(); const updated={...existing,customerStatus:input.targetStatus,objectRecord:{...existing.objectRecord,status:CORE_CUSTOMER_STATUS_TO_OBJECT_STATUS[input.targetStatus],auditMetadata:{...existing.objectRecord.auditMetadata,updatedAt:now,updatedByReferenceId:input.governance.audit.actorReferenceId},version: existing.objectRecord.version ? {...existing.objectRecord.version,updatedAt:now}: undefined}}; const event=this.deps.eventTracePort.append({auditContextReferenceId:input.governance.auditContextReferenceId,visibility:'Internal',event:{id:this.deps.eventIdFactory('changeCustomerStatus',input.customerReferenceId,input.idempotencyKey ?? ''),type:createCoreEventType('core-object-status-changed'),action:CORE_EVENT_ACTIONS.statusChanged,domainId:'customer',object:{id:createCoreObjectId(input.customerReferenceId),type:createCoreObjectType('customer-record'),domainId:'customer'},source:{actorType:'service',actorId:CONTRACT_ID},occurredAt:now,correlationId:input.governance.correlationId,payload:{customerReferenceId:input.customerReferenceId,previousStatus:existing.customerStatus,newStatus:input.targetStatus,reasonReference:input.reasonReference??null}}}); if(!event.ok) return safe<CoreCustomerServiceRecord>('EventTraceFailed','Event trace failed.',input.governance.correlationId); return this.deps.store.replace(updated); }); return idem.ok ? idem.value.result : idem; }

}
