export const CORE_ERROR_CATEGORIES = [
  'Request',
  'Authentication',
  'Authorization',
  'Permission',
  'Policy',
  'Validation',
  'Reference',
  'State',
  'Conflict',
  'Idempotency',
  'Version',
  'RestrictedData',
  'HumanReview',
  'Agent',
  'Workflow',
  'Event',
  'Service',
  'ExternalDependency',
  'RateLimit',
  'Timeout',
  'Internal',
  'Unknown'
] as const;

export const CORE_ERROR_CODES = [
  'BadRequest',
  'Unauthorized',
  'Forbidden',
  'PermissionDenied',
  'PolicyRestricted',
  'ValidationFailed',
  'ReferenceInvalid',
  'ReferenceNotFound',
  'ReferenceTypeMismatch',
  'ReferenceDomainMismatch',
  'StateInvalid',
  'StateTransitionNotAllowed',
  'Conflict',
  'DuplicateRejected',
  'IdempotencyConflict',
  'IdempotencyKeyRequired',
  'IdempotencyKeyInvalid',
  'IdempotencyExpired',
  'VersionUnsupported',
  'RestrictedFieldViolation',
  'RestrictedDataRequested',
  'HumanReviewRequired',
  'AgentContractRequired',
  'AgentSuspended',
  'AgentRevoked',
  'CapabilityNotAllowed',
  'WorkflowReferenceInvalid',
  'TaskReferenceInvalid',
  'EventReferenceInvalid',
  'DownstreamServiceRequired',
  'ExternalDependencyFailed',
  'RateLimited',
  'Timeout',
  'InternalError',
  'CustomerAlreadyExists',
  'CustomerNotFound',
  'InvalidCustomerType',
  'InvalidCustomerStatus',
  'InvalidCustomerTransition',
  'InvalidCustomerReference',
  'CustomerNameRequired',
  'CustomerSourceReferenceRequired',
  'CustomerReasonReferenceRequired',
  'CustomerObjectMismatch',
  'BrandAlreadyExists',
  'BrandNotFound',
  'InvalidBrandType',
  'InvalidBrandStatus',
  'InvalidBrandTransition',
  'InvalidBrandReference',
  'InvalidBrandCustomerReference',
  'BrandNameRequired',
  'BrandSourceReferenceRequired',
  'BrandReasonReferenceRequired',
  'BrandObjectMismatch',
  'TrademarkAlreadyExists',
  'TrademarkNotFound',
  'InvalidTrademarkType',
  'InvalidTrademarkStatus',
  'InvalidTrademarkTransition',
  'InvalidTrademarkReference',
  'InvalidTrademarkBrandReference',
  'InvalidTrademarkJurisdictionReference',
  'TrademarkMarkRepresentationRequired',
  'TrademarkSourceReferenceRequired',
  'TrademarkReasonReferenceRequired',
  'TrademarkObjectMismatch',
  'JurisdictionAlreadyExists',
  'JurisdictionCodeAlreadyExists',
  'JurisdictionNotFound',
  'InvalidJurisdictionType',
  'InvalidJurisdictionStatus',
  'InvalidJurisdictionTransition',
  'InvalidJurisdictionReference',
  'InvalidJurisdictionCode',
  'JurisdictionNameRequired',
  'JurisdictionSourceReferenceRequired',
  'JurisdictionReasonReferenceRequired',
  'JurisdictionObjectMismatch',
  'ClassificationAlreadyExists',
  'ClassificationNotFound',
  'InvalidClassificationScheme',
  'InvalidClassificationStatus',
  'InvalidClassificationReviewStatus',
  'InvalidClassificationTransition',
  'InvalidClassificationReference',
  'InvalidClassificationTrademarkReference',
  'InvalidClassificationBrandReference',
  'InvalidClassificationJurisdictionReference',
  'ClassReferenceRequired',
  'GoodsServicesItemsRequired',
  'ClassNumberOnlyNotAllowed',
  'InvalidClassificationItemType',
  'InvalidClassificationItemReference',
  'ClassificationSourceReferenceRequired',
  'ClassificationReasonReferenceRequired',
  'ClassificationObjectMismatch',
  'DocumentAlreadyExists',
  'DocumentNotFound',
  'InvalidDocumentType',
  'InvalidDocumentStatus',
  'InvalidDocumentReviewStatus',
  'InvalidDocumentConfidentialityLevel',
  'InvalidDocumentTransition',
  'InvalidDocumentReference',
  'DocumentTitleRequired',
  'DocumentSourceReferenceRequired',
  'DocumentFileReferenceRequired',
  'DocumentFileAlreadyLinked',
  'DocumentReviewNoteRequired',
  'DocumentReasonReferenceRequired',
  'DocumentObjectMismatch',
  'EvidenceAlreadyExists',
  'EvidenceNotFound',
  'InvalidEvidenceType',
  'InvalidEvidencePurpose',
  'InvalidEvidenceStatus',
  'InvalidEvidenceReviewStatus',
  'InvalidEvidenceSourceType',
  'InvalidEvidenceSourceReliability',
  'InvalidEvidenceConfidentialityLevel',
  'InvalidEvidenceTransition',
  'InvalidEvidenceReference',
  'InvalidEvidenceSourceReference',
  'InvalidEvidenceClaimReference',
  'InvalidEvidenceDocumentReference',
  'EvidencePurposeRequired',
  'EvidenceSourceRequired',
  'EvidenceSourceAlreadyLinked',
  'EvidenceClaimAlreadyLinked',
  'EvidenceDocumentAlreadyLinked',
  'EvidenceReviewNoteRequired',
  'EvidenceReasonReferenceRequired',
  'EvidenceObjectMismatch',
  'MatterAlreadyExists',
  'MatterNotFound',
  'InvalidMatterType',
  'InvalidMatterStatus',
  'InvalidMatterTransition',
  'InvalidMatterReference',
  'InvalidMatterOrderReference',
  'InvalidMatterCustomerReference',
  'InvalidMatterBrandReference',
  'InvalidMatterTrademarkReference',
  'InvalidMatterWorkflowContractReference',
  'InvalidMatterTaskReference',
  'InvalidMatterDocumentReference',
  'InvalidMatterEvidenceReference',
  'InvalidMatterOrderLinkType',
  'MatterTitleRequired',
  'MatterSourceReferenceRequired',
  'MatterReasonReferenceRequired',
  'MatterRelationshipAlreadyLinked',
  'MatterObjectMismatch',
  'OrderAlreadyExists',
  'OrderNotFound',
  'InvalidOrderType',
  'InvalidOrderStatus',
  'InvalidOrderTransition',
  'InvalidOrderReference',
  'InvalidOrderCustomerReference',
  'InvalidOrderOpportunityReference',
  'InvalidOrderBrandReference',
  'InvalidOrderTrademarkReference',
  'InvalidOrderMatterReference',
  'InvalidOrderCustomerLinkType',
  'InvalidOrderMatterLinkType',
  'OrderTitleRequired',
  'OrderServiceScopeRequired',
  'OrderSourceReferenceRequired',
  'OrderCustomerRequired',
  'OrderReasonReferenceRequired',
  'OrderRelationshipAlreadyLinked',
  'OrderObjectMismatch',
  'OpportunityAlreadyExists',
  'OpportunityNotFound',
  'InvalidOpportunityType',
  'InvalidOpportunityStatus',
  'InvalidOpportunityTransition',
  'InvalidOpportunityReference',
  'InvalidOpportunitySourceType',
  'InvalidOpportunityQualificationStatus',
  'InvalidOpportunityPriority',
  'InvalidOpportunityCustomerReference',
  'InvalidOpportunityBrandReference',
  'InvalidOpportunityTrademarkReference',
  'InvalidOpportunityCommunicationReference',
  'InvalidOpportunityOrderReference',
  'InvalidOpportunityRequestingService',
  'OpportunityTitleRequired',
  'OpportunitySourceReferenceRequired',
  'OpportunityReasonReferenceRequired',
  'OpportunityQualificationReasonRequired',
  'OpportunityQualificationRequired',
  'OpportunityConversionContextRequired',
  'OpportunityConversionRequired',
  'OpportunityRelationshipAlreadyLinked',
  'OpportunityObjectMismatch',
  'EventAlreadyExists',
  'EventNotFound',
  'InvalidEventType',
  'InvalidEventAction',
  'InvalidEventCategory',
  'InvalidEventStatus',
  'InvalidEventTransition',
  'InvalidEventReference',
  'InvalidEventRequestingService',
  'InvalidEventSource',
  'InvalidEventSourceObjectReference',
  'InvalidEventActorContext',
  'InvalidEventPayload',
  'InvalidEventPayloadContractReference',
  'InvalidEventOrganizationReference',
  'InvalidEventDispatchState',
  'InvalidEventDispatchReference',
  'InvalidEventConsumerReference',
  'InvalidEventRecord',
  'EventReasonReferenceRequired',
  'EventConsumerAlreadyLinked',
  'EventObjectMismatch',
  'AuditContextMissing',
  'EventTraceFailed',
  'TaskObjectMismatch',
  'TaskAlreadyExists',
  'TaskNotFound',
  'InvalidTaskType',
  'InvalidTaskStatus',
  'InvalidTaskPriority',
  'InvalidTaskTransition',
  'InvalidTaskReference',
  'InvalidTaskRecord',
  'InvalidTaskAssigneeType',
  'InvalidTaskAssignment',
  'InvalidTaskRelationshipReference',
  'InvalidTaskDependencyReference',
  'TaskTitleRequired',
  'TaskSourceReferenceRequired',
  'TaskReasonReferenceRequired',
  'TaskAssignmentRequired',
  'TaskAlreadyAssigned',
  'TaskNotAssigned',
  'TaskRelationshipAlreadyLinked',
  'TaskCompletionContextRequired',
  'TaskCompletionRequirementsNotMet',
  'TaskWorkflowValidationRequired',
  'TaskHumanReviewRequired',
  'TaskTraceFailed',
  'WorkflowContractObjectMismatch',
  'WorkflowContractAlreadyExists',
  'WorkflowContractNotFound',
  'InvalidWorkflowContractType',
  'InvalidWorkflowContractStatus',
  'InvalidWorkflowContractTransition',
  'InvalidWorkflowContractReference',
  'InvalidWorkflowContractRequestingService',
  'WorkflowContractNameRequired',
  'ApplicableDomainRequired',
  'ApplicableObjectTypeRequired',
  'StateDefinitionsRequired',
  'TransitionDefinitionsRequired',
  'InvalidStateDefinition',
  'InvalidTransitionDefinition',
  'InvalidGuardDefinition',
  'WorkflowContractSourceReferenceRequired',
  'WorkflowContractReasonReferenceRequired',
  'WorkflowContractHumanReviewRequired',
  'WorkflowContractTraceFailed',
  'CommunicationObjectMismatch',
  'CommunicationAlreadyExists',
  'CommunicationNotFound',
  'InvalidCommunicationType',
  'InvalidCommunicationStatus',
  'InvalidCommunicationDirection',
  'InvalidCommunicationChannel',
  'InvalidCommunicationTransition',
  'InvalidCommunicationReference',
  'InvalidCommunicationRequestingService',
  'InvalidCommunicationRecord',
  'InvalidCommunicationRelationshipReference',
  'ChannelReferenceRequired',
  'ParticipantReferenceRequired',
  'InvalidParticipantReference',
  'AttachmentReferenceInvalid',
  'OutboundReviewRequired',
  'DeliveryContextRequired',
  'CommunicationSourceReferenceRequired',
  'CommunicationReasonReferenceRequired',
  'CommunicationAISourceRequired',
  'CommunicationRelationshipAlreadyLinked',
  'CommunicationTraceFailed',
  'IdentityObjectMismatch',
  'IdentityAlreadyExists',
  'IdentityNotFound',
  'InvalidIdentityType',
  'InvalidIdentityStatus',
  'InvalidIdentityTransition',
  'InvalidIdentityReference',
  'InvalidIdentityRequestingService',
  'InvalidIdentityRecord',
  'InvalidIdentityDisplayReference',
  'IdentitySourceReferenceRequired',
  'InvalidIdentityLinkType',
  'InvalidLinkTarget',
  'DuplicateIdentityLink',
  'IdentityReasonReferenceRequired',
  'IdentityHumanCreationReviewRequired',
  'InvalidIdentityResolveReference',
  'IdentityTraceFailed',
  'OrganizationObjectMismatch',
  'OrganizationAlreadyExists',
  'OrganizationNotFound',
  'InvalidOrganizationType',
  'InvalidOrganizationStatus',
  'InvalidOrganizationTransition',
  'InvalidOrganizationReference',
  'InvalidOrganizationRequestingService',
  'InvalidOrganizationRecord',
  'OrganizationNameReferenceRequired',
  'OrganizationSourceReferenceRequired',
  'OrganizationReasonReferenceRequired',
  'OrganizationCreationReviewRequired',
  'InvalidOrganizationUserLinkType',
  'InvalidUserReference',
  'DuplicateOrganizationUserLink',
  'OrganizationUserLinkNotFound',
  'InvalidOrganizationResolveReference',
  'OrganizationTraceFailed',
  'UserObjectMismatch',
  'UserAlreadyExists',
  'UserNotFound',
  'InvalidUserType',
  'InvalidUserStatus',
  'InvalidUserTransition',
  'InvalidUserRequestingService',
  'InvalidUserRecord',
  'UserDisplayNameReferenceRequired',
  'UserSourceReferenceRequired',
  'UserReasonReferenceRequired',
  'UserCreationReviewRequired',
  'IdentityRequired',
  'DuplicateUserIdentityLink',
  'InvalidUserOrganizationLinkType',
  'DuplicateUserOrganizationLink',
  'UserOrganizationLinkNotFound',
  'InvalidUserResolveReference',
  'UserTraceFailed',
  'PermissionObjectMismatch',
  'PermissionAlreadyExists',
  'PermissionNotFound',
  'InvalidPermissionType',
  'InvalidPermissionStatus',
  'InvalidPermissionTransition',
  'InvalidPermissionReference',
  'InvalidPermissionRequestingService',
  'InvalidPermissionRecord',
  'ActorReferenceRequired',
  'InvalidActorReference',
  'ActionRequired',
  'InvalidPermissionAction',
  'ResourceTypeRequired',
  'ResourceReferenceRequired',
  'InvalidResourceReference',
  'ScopeReferenceRequired',
  'InvalidPermissionEffect',
  'PermissionSourceReferenceRequired',
  'PermissionReasonReferenceRequired',
  'PermissionCreationReviewRequired',
  'PermissionEscalationReviewRequired',
  'PermissionSelfGrantNotAllowed',
  'PermissionTraceFailed',
  'UnknownError'
] as const;

export type CoreErrorCategory = (typeof CORE_ERROR_CATEGORIES)[number];
export type CoreErrorCode = (typeof CORE_ERROR_CODES)[number];

export interface CoreSafeError {
  readonly code: CoreErrorCode;
  readonly category: CoreErrorCategory;
  readonly message: string;
  readonly safeDetail: string | null;
  readonly retryable: boolean;
  readonly correlationId: string | null;
}

const unsafePatterns = [
  /\b(stack|stacktrace|traceback)\b/i,
  /\b(sql|select|insert|update|delete|postgres|mysql|sqlite)\b/i,
  /\b(api[-_ ]?key|authorization|bearer|password|secret|token)\b/i,
  /\b(system prompt|hidden instruction|model prompt|tool call)\b/i,
  /\b(database|primary key|internal id)\b/i,
  /\bat\s+\S+\s*\([^)]*:\d+:\d+\)/i
] as const;

function safeText(value: string | null | undefined): string | null {
  if (value === null || value === undefined) return null;
  const normalized = value.trim();
  if (normalized.length === 0 || normalized.length > 500) return null;
  if (unsafePatterns.some((pattern) => pattern.test(normalized))) return null;
  return normalized;
}

export function createCoreSafeError(input: {
  readonly code: CoreErrorCode;
  readonly category: CoreErrorCategory;
  readonly message: string;
  readonly safeDetail?: string | null;
  readonly retryable?: boolean;
  readonly correlationId?: string | null;
}): CoreSafeError {
  const message =
    safeText(input.message) ?? 'The operation could not be completed safely.';
  return Object.freeze({
    code: input.code,
    category: input.category,
    message,
    safeDetail: safeText(input.safeDetail),
    retryable: input.retryable ?? false,
    correlationId: safeText(input.correlationId)
  });
}

export type CoreBehaviorResult<T> =
  | { readonly ok: true; readonly value: T }
  | { readonly ok: false; readonly error: CoreSafeError };
